### PR TITLE
Adds check for EIP 55 format

### PR DESCRIPTION
**Pull request by krhoda**
Adds a check that rejects addresses not formatted in EIP 55, and formats the address into EIP 55 before creating the string message.

Will need this PR to be complete before the tests will pass: https://github.com/spruceid/siwe/pull/51

### CODE REVIEW

**Comment by awoie** [comment]
potentially fixes #53

**Review by theosirian — APPROVED** [review]

**Comment by theosirian** [comment]
We need to move the proposed code into a function that will be called by both parser objects, to avoid restructuring the tests; they operate directly with the parser objects and since the code is in the `SiweMessage` constructor, the negative test will not pass.

**Comment by krhoda** [comment]
I see three ways to accommodate the changes @theosirian needs:

1) Move EIP-55 checks and testing to the siwe level instead of the parser level. Downside: The parser lib doesn’t promise correct EIP-55 formatting.

2) Support EIP-55 checks at the parser level using utils.getAddress. Downside: The parser lib now depends on a single function from ethers.

3) Implement EIP-55 checks at the parser level using Regex and ABNF. Downside: I’m not sure it’s possible.

The actual changes are tiny, just not sure where we want to make them. If we _can_ put them at the parser level in regex or ABNF, that'd be ideal. Does anyone know how?

**Comment by w4ll3** [comment]
Adressed at #62

**Pull request closed without merging**
